# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='Location not given', max_length=255),
            preserve_default=False,
        ),
    ]
