# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0004_auto_20180718_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_path',
        ),
        migrations.AddField(
            model_name='post',
            name='image_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
