# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0005_auto_20180718_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_data',
            new_name='image',
        ),
    ]
