# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0007_auto_20180718_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='poster',
        ),
    ]
