# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-21 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0009_user_upload_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagePath',
            field=models.CharField(default='', max_length=255),
        ),
    ]
